spring.application.name=devisgenerator
spring.profiles.active=dev

jwt.secret=${JWT_SECRET}
jwt.expiration=${JWT_EXPIRATION}

company.name=DevisGenerator
company.address=10 rue de Paris, 75000 Paris
company.email=contact@devisgenerator.fr
company.phone=01 05 13 44 85

frontend.url=${FRONTEND_URL}