spring.datasource.url=jdbc:postgresql://192.168.1.5:5432/devis_db
spring.datasource.username=devis_user
spring.datasource.password=dev1sUs3r

jwt.secret=6hHwa34HWr1bsT1YpokGTGp5uLTcg9XyJxbLd3lerNc=
jwt.expiration=86400000

spring.jpa.hibernate.ddl-auto=none
spring.jpa.show-sql=false
spring.flyway.enabled=false